export enum SearchModes {
  SEARCH = 'search',
  ACTIVE = 'active',
  INACTIVE = 'inactive',
}

export const PRODUCT_MANAGEMENT = {
  API_URL: 'http://localhost:8080/api/prices',
  SEARCH_BY_SKU: 'sku?productSKU=',
  ADD_ROUTE: '/add',
  EDIT_ROUTE: 'edit/',
  DETAILS_ROUTE: '/product/',
  IMPORT_ROUTE: '/import',
  LIST_ROUTE: 'products',
  KEY_ID: 'id',
  KEY_NEW: 'new',
  KEY_EDIT: 'edit',
  KEY_SAVE: 'Save',
  KEY_UPDATE: 'Update',
  KEY_CLASS: 'class',
  KEY_ACTIVE: 'active',
  KEY_INACTIVE: 'inactive',
  ADD_PRODUCT_TITLE: 'Add new product',
  EDIT_PRODUCT_TITLE: 'Edit product',
  SUCCESS: 'Success!',
  WARNING: 'Warning!',
  MESSAGES: {
    ACTIVATE_SUCCESS: 'Product status was updated successfully!',
    UPDATE_SUCCESS: 'Product details was updated successfully!',
    SAVE_SUCCESS: 'Product details was saved successfully!',
    IMPORT_SUCCESS: 'Product details was imported successfully!',
    INVALID_FORM: 'Please enter the valid details',
    DELETE_SUCCESS: 'Product was deleted successfully!',
    DELETE_ALL_SUCCESS: 'All product details was deleted successfully!',
  },
  USER_DETAILS: {
    USER_NAME: 'Admin',
    USER_ID: 'ADM',
  },
  ALPHA_NUMERIC_PATTERN: '^[a-zA-Z0-9]{10}$',
};
